"""init

Revision ID: 0ac2c65167e2
Revises: 
Create Date: 2025-07-15 10:38:18.036892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac2c65167e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('app_bundle', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('tasks_id_idx'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tasks_id_idx'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
